job-android-upload:

  stage: deploy
  tags: [ "deploy" ]

  only:
    - schedules
  dependencies:
    - job-android

  script:
    - cd app/build/outputs/apk/ && rsync ./debug/*.apk $DEPLOY_SERVER:$ANDROID_DEPLOY_DIRECTORY